### ISSUE TITLE
Returning to hashed urls

### ISSUE THREAD

**Issue by kylegodbey** [massexplorer/bmex-masses#2]
@landonbuskirk , is the code that is commented out implementing the hashed urls in a database complete? I was returning to that to make a prettier URL for the paper but I don't wanna break anything this close to release

**Comment by landonbuskirk** [comment]
@kylegodbey Not quite. The commented Python code should work as intended, however, we never properly set up the SQL database in a container that could persist after builds.

**Comment by kylegodbey** [comment]
Yeah I'm not sure what the best workflow is. In the docker compose on the server I added a volume that links to a directory called bmex-db in the git repo root.

Make in the database handler in the webapp we:

1) Check if bmex-db/views-db.sql exists (or whatever the name)
2) Create it if it doesn't 
3) load it as the views-db

This will then be the workflow in the future if we add any more databases for other features (unless we decide to shove everything in one).

Thoughts?

**Comment by landonbuskirk** [comment]
Sounds good to me!

**Comment by kylegodbey** [comment]
@landonbuskirk I think the db stuff is loading correctly, but I'm not getting saved URLs. If you have an idea where the bug is, point me in the right direction and I can look.

**Comment by landonbuskirk** [comment]
@kylegodbey What do you mean by you're not getting saved urls? Is the database is remaining empty?

**Comment by kylegodbey** [comment]
![image](https://github.com/massexplorer/bmex-masses/assets/5806808/d5c7eef3-ad0a-492a-ac01-9e1a44217610)

When I click the little copy button I don't get anything added to my clipboard. It does seem to add something to the database, however

**Comment by landonbuskirk** [comment]
When I open bmex on my phone it copies perfectly, but on my laptop, it does what you described. If I open the console in my browser I get this eeror when the clipboard button is pressed: "Clipboard.react.js:2 Uncaught (in promise) DOMException: The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details."

**Comment by landonbuskirk** [comment]
Not sure if this will help with that permission issue, but I wanted to change the button to a JavaScript component eventually to give us more styling options.

**Comment by kylegodbey** [comment]
Ah, seems like chrome (and other browsers) have some limitations on so-called cross-site permissions. I will try their fix to see if it works. It'll be on the bmex-static side of things since we have an iframe that wraps the webapp

**Comment by kylegodbey** [comment]
Got it fixed! Closing now.
