### ISSUE TITLE
Graph updating behavior when NA is returned from query

### ISSUE THREAD

**Issue by mosesyhc** [massexplorer/bmex-masses#3]
In selecting a new quantity in graph plotting, I believe there is no indication or graph update for missing data.
e.g., if I have first selected 1D Chains, Isotonic EXP Diff, Binding Energy, N=24, ME2, and then select Dataset = AME2020, no change is observed while the previous graph is still up.

**Comment by landonbuskirk** [comment]
Thank you for submitting an issue! When a query returns no values, the graphs should update to a blank plot. What you spotted in your example was an actual error being thrown. I pushed a fix to this error. Also, to make it more clear to the user that AME2020 shouldn't give any interesting result in the EXP Diff plots, I disabled the AME2020 option in the dataset dropdown when considering these plots and added tooltips to the graph dimension/chain types.
